@baseUrl = http://ec2-54-70-149-21.us-west-2.compute.amazonaws.com:9200
# @baseUrl = http://localhost:9200

###
GET {{baseUrl}}/_cat/indices

### list datasource
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "show datasources"
}

### create datasource
POST {{baseUrl}}/_plugins/_query/_datasources
Content-Type: application/x-ndjson

{
  "name": "my_glue",
  "description": "",
  "connector": "S3GLUE",
  "allowedRoles": [],
  "properties": {
    "glue.auth.type": "iam_role",
    "glue.auth.role_arn": "arn:aws:iam::924196221507:role/FlintOpensearchServiceRole",
    "glue.indexstore.opensearch.uri": "http://ec2-54-70-136-129.us-west-2.compute.amazonaws.com:9200",
    "glue.indexstore.opensearch.region": "us-west-2",
    "glue.indexstore.opensearch.auth": "noauth"
  }
}

### get datasource
GET {{baseUrl}}/_plugins/_query/_datasources/my_glue

###
DELETE  {{baseUrl}}/_plugins/_query/_datasources/my_glue

###
DELETE {{baseUrl}}/.query_execution_result

###
POST {{baseUrl}}/_plugins/_async_query
Content-Type: application/x-ndjson

{
  "lang": "sql",
  "query": "select * from my_glue.default.http_logs limit 1"
}


###
POST {{baseUrl}}/_plugins/_async_query
Content-Type: application/x-ndjson

{
  "lang": "sql",
  "query": "create skipping index on my_glue.default.http_logs_streaming (status VALUE_SET) with (auto_refresh = true)"
}

###
GET {{baseUrl}}/_plugins/_async_query/00fdlus8c23h480q


###
DELETE {{baseUrl}}/flint_my_glue_default_http_logs_streaming_skipping_index
