@baseUrl = http://ec2-54-70-136-129.us-west-2.compute.amazonaws.com:9200
# @baseUrl = http://localhost:9200

###
GET {{baseUrl}}/_cat/indices

### list datasource
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "show datasources"
}

### create datasource
POST {{baseUrl}}/_plugins/_query/_datasources
Content-Type: application/x-ndjson

{
  "name": "my_glue",
  "description": "",
  "connector": "S3GLUE",
  "allowedRoles": [],
  "properties": {
    "glue.auth.type": "iam_role",
    "glue.auth.role_arn": "arn:aws:iam::924196221507:role/FlintOpensearchServiceRole",
    "glue.indexstore.opensearch.uri": "http://ec2-54-70-136-129.us-west-2.compute.amazonaws.com:9200",
    "glue.indexstore.opensearch.region": "us-west-2",
    "glue.indexstore.opensearch.auth": "noauth",
    "glue.datasource.spark.config": "--conf spark.dynamicAllocation.enabled=false --conf spark.executor.instances=10"
  }
}

### get datasource
GET {{baseUrl}}/_plugins/_query/_datasources/my_glue

###
DELETE  {{baseUrl}}/_plugins/_query/_datasources/my_glue

###
DELETE {{baseUrl}}/.query_execution_result

###
DELETE {{baseUrl}}/datasource_repl_index

###
PUT {{baseUrl}}/datasource_repl_index
Content-Type: application/x-ndjson

{
  "settings": {
    "number_of_shards": "1",
    "number_of_replicas": "0"
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      "type": {
        "type": "keyword"
      },
      "state": {
        "type": "keyword"
      },
      "sessionId": {
        "type": "keyword"
      },
      "jobId": {
        "type": "keyword"
      },
      "applicationId": {
        "type": "keyword"
      },
      "query": {
        "type": "keyword"
      },
      "submitTime": {
        "type": "long" 
      }
    }
  }
}


###
POST {{baseUrl}}/_plugins/_async_query
Content-Type: application/x-ndjson

{
  "lang": "sql",
  "query": "select * from my_glue.default.http_logs limit 1"
}

###
GET {{baseUrl}}/_plugins/_async_query/REPL0298983865


###
GET {{baseUrl}}/datasource_repl_index/_search


###
GET {{baseUrl}}/datasource_repl_index/_search
Content-Type: application/x-ndjson

{
  "size": 1,
  "sort": [
    {
      "submitTime": {
        "order": "asc"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        { "term": { "state": "RUNNING" } },
        { "term": { "type": "request" } }
      ]
    }
  }
}


###
GET  {{baseUrl}}/.query_execution_result/_search
