@baseUrl = http://ec2-54-70-149-21.us-west-2.compute.amazonaws.com:9200

###
GET {{baseUrl}}/_cat/indices

###
DELETE {{baseUrl}}/query_submit

###
DELETE {{baseUrl}}/query_result

###
PUT {{baseUrl}}/query_submit

###
POST {{baseUrl}}/query_submit/_doc/1
Content-Type: application/x-ndjson

{
  "id": 1,
  "status": "pending",
  "query": "refresh skipping index on default.http_logs"
}

###
POST {{baseUrl}}/query_submit/_search

###
POST {{baseUrl}}/query_submit/_delete_by_query
Content-Type: application/x-ndjson

{
  "query": {
    "match_all": {}
  }
}


###
POST {{baseUrl}}/query_submit/_search
Content-Type: application/x-ndjson

{
  "query": {
      "term": {
          "id": {
              "value": "1"
          }
      }
  }
}


###
POST {{baseUrl}}/query_results/_search
Content-Type: application/x-ndjson

{
  "from": 0,
  "size": 50,
  
    "query": {
        "term": {
            "stepId": {
                "value": "11"
            }
        }
    }
  
}


###
DELETE  {{baseUrl}}/flint_default_http_logs_skipping_index/


###
POST  {{baseUrl}}/flint_default_http_logs_skipping_index/_search
